<?php
$postCollection = $block->getViewModel()->getCollection();
if ($postCollection):
?>
    <?php if ($block->getViewModel()->getIsModerator()): ?>
        <div class="forum-logged-moderator">
            <?= $block->escapeHtml(__('You are logged as moderator')) ?>
        </div>
    <?php endif; ?>
    <div class="forum-myaccount-grid-container">
        <?php if (!$postCollection->getSize()): ?>
            <div class="forum-grid-no-data">
                <?= $block->escapeHtml(__('No Data Found')) ?>
            </div>
        <?php else: ?>
            <div class="toolbar top forum-toolbar">
                <?= $block->getPagerHtml() ?>
            </div>
            <div class="forum-sort">
                <?= $block->escapeHtml(__('Sort By')) ?>
                &nbsp;&nbsp;
                <a <?= $block->getViewModel()->getSortType() == 'asc' ? 'class="selected"' : '' ?>
                   href="<?= $block->escapeUrl($block->getViewModel()->getSortUrl('asc')) ?>"><?= $block->escapeHtml(__('Oldest')) ?></a>
                &nbsp;|&nbsp;
                <a <?= $block->getViewModel()->getSortType() == 'desc' ? 'class="selected"' : '' ?>
                   href="<?= $block->escapeUrl($block->getViewModel()->getSortUrl('desc')) ?>"><?= $block->escapeHtml(__('Newest')) ?></a>
            </div>

            <table class="forum-grid forum-list grid forum-my-posts">
                <thead>
                    <tr>
                        <th><?= $block->escapeHtml(__('Post Details')) ?></th>
                        <th width="1%"><?= $block->escapeHtml(__('Action')) ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($postCollection as $post):
                        $parentTopic = $block->getViewModel()->getParentTopic($post);
                    ?>
                        <tr>
                            <td>
                                <div class="forum-myaccount-post-description clearfix">
                                    <span class="forum-myaccount-post-description-topic">
                                        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Ronald2Wing_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'folder_topic.png')) ?>" alt="" />
                                        <?= $block->escapeHtml(__('Parent Topic: "%1"', $parentTopic->getTitle())) ?>
                                    </span>
                                    <span class="forum-myaccount-post-description-posted">
                                        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Ronald2Wing_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'clock_icon.png')) ?>" alt="" />
                                        <?= $block->escapeHtml(__('Posted: %1', $block->getViewModel()->getTimeAccordingToTimeZone($post->getCreatedAt()))) ?>
                                    </span>
                                </div>
                                <div class="forum-myaccount-postdetails">
                                    <?= $post->getContent() ?>
                                </div>
                            </td>
                            <td>
                                <a href="<?= $block->escapeUrl($block->getViewModel()->getDeletePostLink($post)) ?>" class="my-forum-account delete-link">
                                    <span class="nobr"><img src="<?= $block->escapeUrl($block->getViewFileUrl('Ronald2Wing_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'delete_icon.png')) ?>" alt="" />
                                    <?= $block->escapeHtml(__('Delete')) ?></span>
                                </a>
                                <a href="<?= $block->escapeUrl($block->getViewModel()->getEditPostLink($post)) ?>" class="my-forum-account edit-link">
                                    <span class="nobr"><img src="<?= $block->escapeUrl($block->getViewFileUrl('Ronald2Wing_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'edit_icon.png')) ?>" alt="" />
                                    <?= $block->escapeHtml(__('Edit')) ?></span>
                                </a>
                                <a href="<?= $block->escapeUrl($block->getViewModel()->getViewPostLink($post)) ?>" class="my-forum-account view-link">
                                    <span class="nobr"><img src="<?= $block->escapeUrl($block->getViewFileUrl('Ronald2Wing_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'view_icon.png')) ?>" alt="" />
                                    <?= $block->escapeHtml(__('View')) ?></span>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>
        <div class="clearfix back-to-forum-url">
            <a href="<?= $block->escapeUrl($block->getViewModel()->getForumUrl()) ?>">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('Ronald2Wing_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'back_icon.png')) ?>" alt="" />
                <?= $block->escapeHtml(__('Back to Forum')) ?>
            </a>
        </div>
    </div>
<?php endif; ?>
