<?php
$forums = $block->getViewModel()->getDisplayForums();
?>
<div class="forum-list-container clearfix">
    <h3 class="grid-title">
        <?= $block->escapeHtml(__('Viewing All Forums')) ?>
    </h3>
    <?php if (!$forums->getSize()): ?>
        <div class="forum-grid-no-data">
            <?= $block->escapeHtml(__('No Data Found')) ?>
        </div>
    <?php else: ?>
        <div class="toolbar top forum-toolbar">
            <?= $block->getPagerHtml() ?>
        </div>
        <div class="forum-sort">
            <?= $block->escapeHtml(__('Sort By')) ?>
            &nbsp;&nbsp;
            <a <?= $block->getViewModel()->getSortType() == 'asc' ? 'class="selected"' : '' ?>
               href="<?= $block->escapeUrl($block->getViewModel()->getSortUrl('asc')) ?>"><?= $block->escapeHtml(__('Oldest')) ?></a>
            &nbsp;|&nbsp;
            <a <?= $block->getViewModel()->getSortType() == 'desc' ? 'class="selected"' : '' ?>
               href="<?= $block->escapeUrl($block->getViewModel()->getSortUrl('desc')) ?>"><?= $block->escapeHtml(__('Newest')) ?></a>
        </div>
        <table class="forum-grid forum-list grid data-table-forum-resp">
            <thead>
                <tr>
                    <th width="35%"><?= $block->escapeHtml(__('Forum')) ?></th>
                    <th width="15%"><?= $block->escapeHtml(__('Total Topics')) ?></th>
                    <th width="15%"><?= $block->escapeHtml(__('Total Posts')) ?></th>
                    <th width="35%"><?= $block->escapeHtml(__('Latest Reply')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($forums as $forum): ?>
                    <tr>
                        <td>
                            <div>
                                <div class="forum-icons">
                                    <img src="<?= $block->escapeUrl($block->getViewFileUrl('Ronald2Wing_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'folder_forum.png')) ?>" alt="" />
                                    <?php if ($block->getViewModel()->getIsIconsEnabled() && $block->getViewModel()->getIcon($forum)): ?>
                                        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Ronald2Wing_Forum' . DIRECTORY_SEPARATOR . $block->getViewModel()->getIcon($forum))) ?>" alt="" />
                                    <?php endif; ?>
                                </div>
                                <div class="forum-details">
                                    <?php if (!$block->getViewModel()->isAllowed($forum->getId()) && !$block->getViewModel()->getIsModerator()): ?>
                                        <strong><?= $block->escapeHtml($forum->getTitle()) ?></strong>
                                    <?php else: ?>
                                        <a class="forum-display-description" href="<?= $block->escapeUrl($block->getViewModel()->getForumViewUrl($forum)) ?>"><?= $block->escapeHtml($forum->getTitle()) ?></a>
                                    <?php endif; ?>
                                    <?php if ($forum->getDescription()): ?>
                                        <div class="forum-topic-description">
                                            <?= $block->escapeHtml($forum->getDescription()) ?>
                                        </div>
                                    <?php endif; ?>
                                    <div class="forum-created-time">
                                        <?= $block->escapeHtml(__('Created')) ?>: <?= $block->escapeHtml($block->getViewModel()->getTimeAccordingToTimeZone($forum->getCreatedAt())) ?>
                                    </div>
                                    <div class="forum-created-by">
                                        <?= $block->escapeHtml(__('Created By: "%1"', $block->getViewModel()->getForumCreatorName($forum))) ?>
                                        (<a href="<?= $block->escapeUrl($block->getViewModel()->getForumCreatorLink($forum)) ?>"><?= $block->escapeHtml($block->getViewModel()->getForumCreatorName($forum)) ?></a>)
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="total-topics-container">
                                <img src="<?= $block->escapeUrl($block->getViewFileUrl('Ronald2Wing_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'folder_topic.png')) ?>" alt="" />
                                <?= (int) $forum->getTotalTopics() ?>
                            </div>
                        </td>
                        <td>
                            <div class="total-posts-container">
                                <img src="<?= $block->escapeUrl($block->getViewFileUrl('Ronald2Wing_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'forum_post.png')) ?>" alt="" />
                                <?= (int) $forum->getTotalPosts() ?>
                            </div>
                        </td>
                        <td>
                            <?php $latest = $block->getViewModel()->getLatestPostDetails($forum->getLastPostId()); ?>
                            <div class="forum-latest-reply">
                                <?php if (!$block->getViewModel()->isAllowed($forum->getId()) && !$block->getViewModel()->getIsModerator()): ?>
                                    <strong><?= $block->escapeHtml(__('Private Forum')) ?></strong>
                                <?php else: ?>
                                    <?php if (!$latest): ?>
                                        <?= $block->escapeHtml(__('No Data Found')) ?>
                                    <?php else: ?>
                                        <?php if ($block->getViewModel()->getIsIconsEnabled() && $block->getViewModel()->getLatestIcon($latest)): ?>
                                            <img src="<?= $block->escapeUrl($block->getViewFileUrl('Ronald2Wing_Forum' . DIRECTORY_SEPARATOR . $block->getViewModel()->getLatestIcon($latest))) ?>" alt="" />
                                        <?php endif; ?>
                                        <a class="forum-display-description" href="<?= $block->escapeUrl($block->getViewModel()->getLatestViewUrl($latest)) ?>"><?= $block->escapeHtml($block->getViewModel()->getLatestTopicTitle($latest)) ?></a>
                                        <?php if ($block->getViewModel()->getLatestTopicDescription($latest)): ?>
                                            <div class="forum-topic-description">
                                                <?= $block->escapeHtml($block->getViewModel()->getLatestTopicDescription($latest)) ?>
                                            </div>
                                        <?php endif; ?>
                                        <div class="forum-latest-reply-date">
                                            <?= $block->escapeHtml(__('Posted: %1', $block->getViewModel()->getLatestPostedDate($latest))) ?>
                                        </div>
                                        <div class="forum-latest-reply-user">
                                            <?= $block->escapeHtml(__('Posted By: %1', $block->getViewModel()->getLatestPostedBy($latest))) ?>
                                            (<a href="<?= $block->escapeUrl($block->getViewModel()->getLatestPostedByUrl($latest)) ?>"><?= $block->escapeHtml($block->getViewModel()->getLatestPostedBy($latest)) ?></a>)
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">
            Ronald2Wing_Forum_Responsive_tables.init();
        </script>
    <?php endif; ?>
</div>
