<script type="text/javascript">
window.onload = function() {
    tinymce.init({
        selector: 'textarea',
        height: 200,
        plugins: [
            'emoticons paste'
        ],
        relative_urls: false,
        remove_script_host: false,
        toolbar1: 'emoticons',
        menubar: false,
        toolbar_items_size: 'small'
    });
};

function ___ronald2wing_showEditor() {
    document.getElementById('ronald2wing-editor').style.display = 'block';
}
function ___ronald2wing_hideEditor() {
    document.getElementById('ronald2wing-editor').style.display = 'none';
}
</script>
